language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

script: php vendor/bin/phpunit
